name: "gridai-run"

on:
  # push:
  pull_request:  
  schedule:
  # run at 13 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 33 0,8,16 * * *

jobs:
  run:
    uses: robert-s-lee/actions/.github/workflows/gridai_run.yml@main
    with:
      script_name: hello.py
    secrets:
      username: ${{ secrets.GRIDAI_USERNAME }} 
      key: ${{ secrets.GRIDAI_KEY }}
