name: "gridai-run"

on:
  # push:
  pull_request:  
  schedule:
  # run at 13 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 33 0,8,16 * * *

jobs:
  gridai-run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: robert-s-lee/gridai_action_login@main
        with:
          gridai_username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai_key: ${{ secrets.GRIDAI_KEY }}
      - uses: actions/checkout@v2
      - run: |
          export run_name=c$(date +'%y%m%d-%H%M%S')
          echo "run_name=${run_name}" >> $GITHUB_ENV 
          grid run --dependency_file requirements.txt --name ${run_name} hello.py
      - id: grid_status
        uses: robert-s-lee/gridai_action_status@main
        with:
          obj_type: run
          obj_id: ${run_name}
      - run: |
          if [ "${{ steps.grid_status.outputs.obj_status }}" != "running" ]; then
            exit 1
          fi   
